name: S3 Log Fetcher

on:
  schedule:
    - cron: '10 0 * * *' # 매일 한국 시간 오전 9시 10분
  workflow_dispatch:      # 수동 실행 버튼 활성화

jobs:
  download-logs:
    runs-on: ubuntu-latest
    # Git Push를 위해 쓰기 권한 추가
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3에서 로그 다운로드
        run: |
          mkdir -p ./downloaded_logs/
          # 경로를 버킷 최상단으로 변경
          aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/ ./downloaded_logs/

      - name: 로그 파일을 아티팩트로 업로드
        uses: actions/upload-artifact@v4
        with:
          name: s3-server-logs          # 다운로드 받을 압축 파일 이름
          path: ./downloaded_logs/      # 보관할 폴더 경로

      - name: 로그 파일을 레포지토리에 커밋
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./downloaded_logs/
          git commit -m "Update server logs from S3: $(date)" || echo "No changes to commit"
          git push
