name: S3 Log Fetcher

on:
  schedule:
    - cron: '10 0 * * *' # 매일 한국 시간 오전 9시 10분 (UTC 00:10)
  workflow_dispatch:      # 수동으로 실행하고 싶을 때 사용

jobs:
  download-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3에서 로그 다운로드
        run: |
          aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/server-logs/ ./downloaded_logs/
